# Stage 1: Dependencies
FROM node:20-alpine AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

COPY package.json .npmrc ./
RUN npm install --legacy-peer-deps

# Stage 2: Builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build with production env vars passed at build time
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APP_NAME
ARG NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ARG NEXT_PUBLIC_MERCHANT_WALLET
ARG NEXT_PUBLIC_USDT_ETHEREUM
ARG NEXT_PUBLIC_USDC_ETHEREUM
ARG NEXT_PUBLIC_USDT_POLYGON
ARG NEXT_PUBLIC_USDC_POLYGON
ARG NEXT_PUBLIC_USDT_BSC
ARG NEXT_PUBLIC_USDC_BSC
ARG NEXT_PUBLIC_USDT_BASE
ARG NEXT_PUBLIC_USDC_BASE

ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_NAME=$NEXT_PUBLIC_APP_NAME
ENV NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID
ENV NEXT_PUBLIC_MERCHANT_WALLET=$NEXT_PUBLIC_MERCHANT_WALLET
ENV NEXT_PUBLIC_USDT_ETHEREUM=$NEXT_PUBLIC_USDT_ETHEREUM
ENV NEXT_PUBLIC_USDC_ETHEREUM=$NEXT_PUBLIC_USDC_ETHEREUM
ENV NEXT_PUBLIC_USDT_POLYGON=$NEXT_PUBLIC_USDT_POLYGON
ENV NEXT_PUBLIC_USDC_POLYGON=$NEXT_PUBLIC_USDC_POLYGON
ENV NEXT_PUBLIC_USDT_BSC=$NEXT_PUBLIC_USDT_BSC
ENV NEXT_PUBLIC_USDC_BSC=$NEXT_PUBLIC_USDC_BSC
ENV NEXT_PUBLIC_USDT_BASE=$NEXT_PUBLIC_USDT_BASE
ENV NEXT_PUBLIC_USDC_BASE=$NEXT_PUBLIC_USDC_BASE

ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

# Stage 3: Runner
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

CMD ["node", "server.js"]
